Versao: '1.0.1'

Configurar:
  Titulos:
    VoceEntrou:
      Titulo: '§a§lChain!'
      Subtitulo: '§eVocê entrou no Chain!'
      Ativar: true
    VoceSaiu:
      Titulo: '§cVoce saiu :('
      Subtitulo: '§ePara voltar ao chain, digite /chain!'
      Ativar: true
    VoceMorreu:
      Titulo: '§eDerrotado!'
      Subtitulo: '§eVocê foi morto no Chain!'
      Ativar: true
  
#Configurações do Chain
  Opcoes:
    AnunciarGlobalEntrou: true
#Essa opção eu fiz pro meu plugin de Almas, ela não remove cabeças do inventario quando o jogador sai do Chain.
    NaoRemoverCabecas: true
    DarMoneyAoMatar: true
    MoneyAoMatar: 500
    BloquearOPlayerDeDroparItem: true
    NaoDroparItemAoMorrer: true
#Opção para ativar os vários sons!
    AtivarSons: true
    EfeitosFogos: true
    EfeitosAoMatar: true
    ExecutarComandosAoMatar:
        - 'broadcast §aO @matou@ matou @morreu@ no Chain!'
        - 'broadcast §aEssa mensagem pode ser editada/removida na config!'
    ExecutarComandosAoSair:
        - 'broadcast §aO @saiu@ saiu do Chain!'
    ExecutarComandosAoEntrar:
        - 'broadcast §aO @entrou@ entrou no Chain. Venha também! /chain entrar!'
        
#Esses efeitos são aplicados para o jogador que matou. Caso não queira nenhum efeito, deixe aspas vazias ' '
#Para adicionar multiplos efeitos, você deve colocar um tracinho. Coloque os efeitos em ordem: EFEITO:NIVEL:DURAÇÂO-EFEITO:NIVEL:DURAÇÂO etc...
    AplicarEfeitosAoMatar: 'speed:5:10-regeneration:2:10'
    
#Quando essa opção estiver true, automaticamente quando um jogador entrar no Chain
#O inventario dele será salvo automaticamente, sem precisar ficar esvaziando o inventario, e ele recebera os itens
#Normais do Chain. Quando ele morrer no Chain ou sair do servidor, ele automaticamente receberá os itens devolta!
    GuardarInventario: true

#Os jogadores que estiverem no Chain só poderão usar os comandos que estiverem listados abaixo.
#Não é necessario por o comando completo, apenas o inicio dele.
    ComandosPermitidos:
      - '/chain'
      - '/g'
      - '/money'
      - '/tell'
      - '/.'