name: SpecterChain
main: com.lucas.specterchain.Main
version: 1.0
description: Plugin de Chain!
authors: [Specter]
commands:
    chain:
        usage: ยง4[Chain] Digite /chain para ver os comandos!
        description: Comandos gerais do plugin.
        aliases: ca